# Site settings
name: ljj's Blog
email: 931781346@qq.com
author: Liao 
url: http://www.baidu.com
resume_site: https://github.com/ljjloghub/
github: https://github.com/ljjloghub/
baseurl: ""
description: Actually, less is more!
meta_description: 廖俊杰;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: ljjbloghub

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

